### ISSUE TITLE
NewSeed can fail to generate valid seed

### ISSUE THREAD

**Issue by knarz** [iotaledger/iota.lib.go#2]
Generating a valid seed can fail whenever the bytes returned are too small to generate a hex string of 81 characters.

```go
func NewSeed() Trytes {
	b := make([]byte, 48)
	if _, err := rand.Read(b); err != nil {
		panic(err)
	}
	txt := new(big.Int).SetBytes(b).Text(27)
	t := make([]rune, 81)
	for i, c := range txt {
```

`txt` here can be `< 81` characters long, which means that we end up with the last rune of `t` being `\x00`.

How to reproduce:
run `for i in {0..100}; do go test -v -race -run TestAddress .; done;` and you're guaranteed to get a couple of invalid seeds.

**Comment by utamaro** [comment]
fixed ( i believe)
