### ISSUE TITLE
Login flow & balances example?

### ISSUE THREAD

**Issue by jdevelop** [iotaledger/iota.lib.go#26]
I'm trying to read the balance of my wallet:

```
package main

import (
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/iotaledger/giota"
)

const Host = "http://node04.iotatoken.nl:14265"

func main() {
	client := http.Client{
		Timeout: 10 * time.Second,
	}
	println("Connecting")
	api := giota.NewAPI(Host, &client)
	seed, err := giota.ToTrytes("very secret seed here")
	if err != nil {
		log.Fatal(err)
	}
	println("Getting balances")
	inputs, err := giota.GetInputs(api, seed, 0, 400, 0, 12)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(inputs)
}
```

This one returns empty slice. Out of sniffing the protocol of the ledger app - it looks like it is trying to fetch all the addressess/bundles associated with the seed and then uses the single call to the `getBalances` command passing on all the addresses.

Can you please provide some example of how to do this with the Go client library?

**Comment by knarz** [comment]
I added an example directory containing a modified version of your code. Please reopen this issue if that is unclear.

**Comment by jdevelop** [comment]
@knarz thanks, while that works for one of the seeds that I have (just created the test wallet), however for **another** one with 80 chars it doesn't return the addresses/balances (still there are some coins available). Just empty address list.

**Comment by knarz** [comment]
Does it work if you add a `9` to the end of that 80 character seed?

**Comment by jdevelop** [comment]
@knarz yes, if I right-pad the seed by `9` - that works! Can you pleas recommend some whitepaper that describes this? I went through the [standard](https://iota.org/IOTA_Whitepaper.pdf) one and it doesn't have much of the implementation details.

**Comment by knarz** [comment]
The whitepaper does not describe the actual protocol used. There is no such document, as far as I know, which is a shame. Your best bet, if you want to understand all the intricacies, is reading the reference implementation code.

But I'll see that I'll add the automatic padding to the seed.

**Comment by jdevelop** [comment]
With the reference implementation code you mean IRI (java) or the current library code?

Side note -  I was thinking about building the server app in Golang, simply because Java kills my raspberry PI. Do you know if this could be planned or something like that?

**Comment by knarz** [comment]
The library does all the heavy lifting.

I'm not sure what exactly you are referring to. Do you mean rewriting IRI in Go? Sure that'd be possible.

**Comment by jdevelop** [comment]
Okay, thanks - so I'll stick with the library for some time. Yes, I am thinking that it would be handy to have the Go version of IRI around, for those who run nodes on RaspberryPI, and also could be interesting to get Broadcom GPU for transaction minting.
