### ISSUE TITLE
Address generation doesn't depend on the seed

### ISSUE THREAD

**Issue by jdevelop** [iotaledger/iota.lib.go#27]
```
package tests

import (
	"testing"

	"github.com/iotaledger/giota"
	"github.com/stretchr/testify/assert"
)

func TestAddressGen(t *testing.T) {
	seed1, err := giota.ToTrytes("SEEDTEST")
	assert.Nil(t, err)
	seed2, err := giota.ToTrytes("TESTSEED")
	assert.Nil(t, err)
	addr1, err := giota.NewAddress(seed1, 1, 2)
	assert.Nil(t, err)
	addr2, err := giota.NewAddress(seed2, 1, 2)
	assert.Nil(t, err)
	assert.NotEqual(t, addr1, addr2)
}
```

This test fails because of the same address value generated for the different seeds. Am I missing something here?

**Comment by Pomyk** [comment]
Those seeds are invalid, should have 81 trytes. NewAddress function should return error in this case.

**Comment by jdevelop** [comment]
Confirmed, with 81 charachter-long seed the results are indeed different. With anything less than 80 chars they are always the same. Should it pad the seeds with `999...` if the seed length is `< 81` ?

**Comment by knarz** [comment]
The wallet allows [`60 <= seed <= 81`](https://github.com/iotaledger/wallet/blob/748c0be8dca03b37ade4d7abbcedf795d864038c/ui/js/ui.login.js#L49).

I'm fine with either padding it automatically or throwing an error.

**Comment by Pomyk** [comment]
I think error is better, wallet doesn't pad by default.

**Comment by knarz** [comment]
`NewKey` should now return an error whenever it is supplied with a seed that is too short
