### ISSUE TITLE
Comments are inconsistent

### ISSUE THREAD

**Issue by deltaskelta** [iotaledger/iota.lib.go#32]
I have noticed some grammatical errors in the comments as well as inconsistent spaces after the `//`'s, and missing comments on exported functions/methods. I would like to go through and fix these and familiarize myself with the code in the process but I just wanted to ask first to make sure the changes are welcome and the project will still be actively developed in the near future

**Comment by knarz** [comment]
Sure, go ahead. I'm a bit busy with other things but I'll try to keep up.
