### ISSUE TITLE
NewAddress generates wrong address compared to iota.lib.js

### ISSUE THREAD

**Issue by tintinweb** [iotaledger/iota.lib.go#5]
Hi,

Either I am doing something wrong or the libray is generating wrong addresses when calling `giota.NewAddress(seed_trytes, 0, 2)`. Below is the output when comparing it with the `iota.lib.js` based electron light wallet.

```golang
trytesFrom:="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
trytes2,err:=giota.ToTrytes(trytesFrom)
adr,err:=giota.NewAddress(trytes2, 0, 2) //without checksum.

//ADDR:  SCRFLYEFBSRTSGYGWQNRUNVBXHDTIWJVGTHOFRTDLYNOQMHMJPVPNQCNQDFSVXNPYCLDCEJEWJVCFBVKS
```

```javascript
iota.api.getNewAddress('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', {index: 0, total: 1, security:2}, function (error, addy) { if(error) { console.log(error); } else { console.log(addy); }});
//ADDR:  XUERGHWTYRTFUYKFKXURKHMFEVLOIFTTCNTXOGLDPCZ9CJLKHROOPGNAQYFJEPGK9OKUQROUECBAVNXRX
```

The address generated by the light wallet looks good (as it has a transaction history)

Please make sure people are not losing funds because of this by adding some unittests to check for address gen inconsistencies.

**Comment by knarz** [comment]
Hello, as stated in the first line of the `README.md`: Please note that this repo has not yet been updated to use Kerl.

i.e. it still generates addresses using the old hashing algorithm.

**Comment by tintinweb** [comment]
Excellent, thank you @knarz. Seems like I've missed that note. Would it make sense to make it a more prominent (e.g. bold and red) until kerl is merged?

Anyway, thanks for the work you put into this project! 👍
